city_list_dict = [{'name': '深圳', 'code': 'sz'}, {'name': '北京', 'code': 'bj'}, {'name': '济南', 'code': 'jn'},
                  {'name': '合肥', 'code': 'hf'}, {'name': '成都', 'code': 'cd'}, {'name': '东莞', 'code': 'dg'},
                  {'name': '南京', 'code': 'nj'}, {'name': '长沙', 'code': 'cs'}, {'name': '武汉', 'code': 'wh'},
                  {'name': '沈阳', 'code': 'sy'}, {'name': '重庆', 'code': 'cq'}, {'name': '大连', 'code': 'dl'},
                  {'name': '天津', 'code': 'tj'}, {'name': '苏州', 'code': 'su'}, {'name': '杭州', 'code': 'hz'},
                  {'name': '广州', 'code': 'gz'}, {'name': '佛山', 'code': 'fs'}, {'name': '青岛', 'code': 'qd'},
                  {'name': '烟台', 'code': 'yt'}, {'name': '厦门', 'code': 'xm'}, {'name': '上海', 'code': 'sh'}]
cities_dict = {
    'bj': '北京',
    'cd': '成都',
    'cq': '重庆',
    'cs': '长沙',
    'dg': '东莞',
    'dl': '大连',
    'fs': '佛山',
    'gz': '广州',
    'hz': '杭州',
    'hf': '合肥',
    'jn': '济南',
    'nj': '南京',
    'qd': '青岛',
    'sh': '上海',
    'sz': '深圳',
    'su': '苏州',
    'sy': '沈阳',
    'tj': '天津',
    'wh': '武汉',
    'xm': '厦门',
    'yt': '烟台',
}
city_code_list = ['bj', 'cd', 'cq', 'cs', 'dg', 'dl',
                  'fs', 'gz', 'hz', 'hf', 'jn', 'nj',
                  'qd', 'sh', 'sz', 'su', 'sy', 'tj',
                  'wh', 'xm', 'yt']
