all_cities = [{'city_name': '北京', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=bj'},
              {'city_name': '上海', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=sh'},
              {'city_name': '重庆', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=cq'},
              {'city_name': '天津', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=tianjin'},
              {'city_name': '广州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=gz'},
              {'city_name': '深圳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=sz'},
              {'city_name': '中山', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zs'},
              {'city_name': '珠海', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zh'},
              {'city_name': '江门', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=jm'},
              {'city_name': '惠州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=huizhou'},
              {'city_name': '东莞', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=dg'},
              {'city_name': '佛山', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=fs'},
              {'city_name': '清远', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=qingyuan'},
              {'city_name': '湛江', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zhanjiang'},
              {'city_name': '阳江', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=yangjiang'},
              {'city_name': '茂名', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=maoming'},
              {'city_name': '肇庆', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zhaoqing'},
              {'city_name': '汕头', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=shantou'},
              {'city_name': '潮州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=chaozhou'},
              {'city_name': '汕尾', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=shanwei'},
              {'city_name': '揭阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=jieyang'},
              {'city_name': '梅州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=meizhou'},
              {'city_name': '云浮', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=yunfu'},
              {'city_name': '韶关', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=shaoguan'},
              {'city_name': '成都', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=cd'},
              {'city_name': '南充', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=nanchong'},
              {'city_name': '泸州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=lz'},
              {'city_name': '绵阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=my'},
              {'city_name': '内江', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=neijiang'},
              {'city_name': '乐山', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=leshan'},
              {'city_name': '武汉', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=wh'},
              {'city_name': '宜昌', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=yichang'},
              {'city_name': '襄阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xiangyang'},
              {'city_name': '恩施', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=enshi'},
              {'city_name': '黄石', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=huangshi'},
              {'city_name': '黄冈', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=huanggang'},
              {'city_name': '鄂州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=ezhou'},
              {'city_name': '荆州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=jingzhou'},
              {'city_name': '十堰', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=shiyan'},
              {'city_name': '荆门', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=jingmen'},
              {'city_name': '仙桃', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xiantao'},
              {'city_name': '孝感', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xiaogan'},
              {'city_name': '咸宁', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xianning'},
              {'city_name': '长沙', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=cs'},
              {'city_name': '株洲', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zhuzhou'},
              {'city_name': '衡阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=hengyang'},
              {'city_name': '湘潭', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xiangtan'},
              {'city_name': '郴州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=chenzhou'},
              {'city_name': '永州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=yongzhou'},
              {'city_name': '岳阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=yueyang'},
              {'city_name': '常德', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=changde'},
              {'city_name': '益阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=yiyang'},
              {'city_name': '邵阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=shaoyang'},
              {'city_name': '郑州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zz'},
              {'city_name': '驻马店', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zhumadian'},
              {'city_name': '洛阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=luoyang'},
              {'city_name': '南阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=nanyang'},
              {'city_name': '许昌', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xuchang'},
              {'city_name': '开封', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=kaifeng'},
              {'city_name': '平顶山', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=pingdingshan'},
              {'city_name': '漯河', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=luohe'},
              {'city_name': '周口', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zhoukou'},
              {'city_name': '南京', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=nj'},
              {'city_name': '苏州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=suzhou'},
              {'city_name': '无锡', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=wuxi'},
              {'city_name': '常州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=changzhou'},
              {'city_name': '扬州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=yangzhou'},
              {'city_name': '镇江', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zhenjiang'},
              {'city_name': '南通', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=nantong'},
              {'city_name': '徐州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xuzhou'},
              {'city_name': '盐城', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=yancheng'},
              {'city_name': '淮安', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=huaian'},
              {'city_name': '宿迁', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=suqian'},
              {'city_name': '泰州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=taizhou'},
              {'city_name': '连云港', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=lianyungang'},
              {'city_name': '石家庄', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=sjz'},
              {'city_name': '唐山', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=tangshan'},
              {'city_name': '张家口', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zjk'},
              {'city_name': '杭州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=hz'},
              {'city_name': '绍兴', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=shaoxing'},
              {'city_name': '宁波', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=nb'},
              {'city_name': '台州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=tz'},
              {'city_name': '金华', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=jinhua'},
              {'city_name': '湖州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=huzhou'},
              {'city_name': '温州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=wenzhou'},
              {'city_name': '嘉兴', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=jiaxing'},
              {'city_name': '舟山', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zhoushan'},
              {'city_name': '丽水', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=ls'},
              {'city_name': '大连', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=dl'},
              {'city_name': '沈阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=sy'},
              {'city_name': '抚顺', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=fushun'},
              {'city_name': '鞍山', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=anshan'},
              {'city_name': '本溪', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=benxi'},
              {'city_name': '铁岭', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=tl'},
              {'city_name': '辽阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=ly'},
              {'city_name': '丹东', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=dandong'},
              {'city_name': '盘锦', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=panjin'},
              {'city_name': '锦州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=jinzhou'},
              {'city_name': '葫芦岛', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=huludao'},
              {'city_name': '朝阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=chaoyang'},
              {'city_name': '聊城', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=lc'},
              {'city_name': '安庆', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=anqing'},
              {'city_name': '马鞍山', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=maanshan'},
              {'city_name': '池州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=chizhou'},
              {'city_name': '西安', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xian'},
              {'city_name': '汉中', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=hanzhong'},
              {'city_name': '咸阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xy'},
              # {'city_name': '渭南', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=wn'},
              {'city_name': '福州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=fuzhou'},
              {'city_name': '厦门', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xiamen'},
              {'city_name': '泉州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=quanzhou'},
              {'city_name': '宁德', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=ningde'},
              {'city_name': '海外地产', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=haiwai'}]

all_city_code = [{'city_code': '1', 'city_name': '北京'},
                 {'city_code': '2', 'city_name': '上海'},
                 {'city_code': '36', 'city_name': '重庆'},
                 {'city_code': '57', 'city_name': '天津'},
                 {'city_code': '3', 'city_name': '广州'},
                 {'city_code': '4', 'city_name': '深圳'},
                 {'city_code': '37', 'city_name': '中山'},
                 {'city_code': '38', 'city_name': '珠海'},
                 {'city_code': '39', 'city_name': '江门'},
                 {'city_code': '41', 'city_name': '惠州'},
                 {'city_code': '42', 'city_name': '东莞'},
                 {'city_code': '43', 'city_name': '佛山'},
                 {'city_code': '89', 'city_name': '清远'},
                 {'city_code': '150', 'city_name': '湛江'},
                 {'city_code': '151', 'city_name': '阳江'},
                 {'city_code': '152', 'city_name': '茂名'},
                 {'city_code': '153', 'city_name': '肇庆'},
                 {'city_code': '169', 'city_name': '汕头'},
                 {'city_code': '170', 'city_name': '潮州'},
                 {'city_code': '171', 'city_name': '汕尾'},
                 {'city_code': '172', 'city_name': '揭阳'},
                 {'city_code': '173', 'city_name': '梅州'},
                 {'city_code': '181', 'city_name': '云浮'},
                 {'city_code': '248', 'city_name': '韶关'},
                 {'city_code': '5', 'city_name': '成都'},
                 {'city_code': '29', 'city_name': '南充'},
                 {'city_code': '30', 'city_name': '泸州'},
                 {'city_code': '31', 'city_name': '绵阳'},
                 {'city_code': '258', 'city_name': '内江'},
                 {'city_code': '261', 'city_name': '乐山'},
                 {'city_code': '6', 'city_name': '武汉'},
                 {'city_code': '95', 'city_name': '宜昌'},
                 {'city_code': '143', 'city_name': '襄阳'},
                 {'city_code': '185', 'city_name': '恩施'},
                 {'city_code': '186', 'city_name': '黄石'},
                 {'city_code': '187', 'city_name': '黄冈'},
                 {'city_code': '188', 'city_name': '鄂州'},
                 {'city_code': '227', 'city_name': '荆州'},
                 {'city_code': '228', 'city_name': '十堰'},
                 {'city_code': '232', 'city_name': '荆门'},
                 {'city_code': '233', 'city_name': '仙桃'},
                 {'city_code': '236', 'city_name': '孝感'},
                 {'city_code': '242', 'city_name': '咸宁'},
                 {'city_code': '7', 'city_name': '长沙'},
                 {'city_code': '21', 'city_name': '株洲'},
                 {'city_code': '22', 'city_name': '衡阳'},
                 {'city_code': '121', 'city_name': '湘潭'},
                 {'city_code': '123', 'city_name': '郴州'},
                 {'city_code': '128', 'city_name': '永州'},
                 {'city_code': '130', 'city_name': '岳阳'},
                 {'city_code': '131', 'city_name': '常德'},
                 {'city_code': '132', 'city_name': '益阳'},
                 {'city_code': '283', 'city_name': '邵阳'},
                 {'city_code': '12', 'city_name': '郑州'},
                 {'city_code': '269', 'city_name': '驻马店'},
                 {'city_code': '141', 'city_name': '洛阳'},
                 {'city_code': '162', 'city_name': '南阳'},
                 {'city_code': '164', 'city_name': '许昌'},
                 {'city_code': '167', 'city_name': '开封'},
                 {'city_code': '245', 'city_name': '平顶山'},
                 {'city_code': '246', 'city_name': '漯河'},
                 {'city_code': '259', 'city_name': '周口'},
                 {'city_code': '13', 'city_name': '南京'},
                 {'city_code': '51', 'city_name': '苏州'},
                 {'city_code': '52', 'city_name': '无锡'},
                 {'city_code': '53', 'city_name': '常州'},
                 {'city_code': '67', 'city_name': '扬州'},
                 {'city_code': '68', 'city_name': '镇江'},
                 {'city_code': '69', 'city_name': '南通'},
                 {'city_code': '70', 'city_name': '徐州'},
                 {'city_code': '71', 'city_name': '盐城'},
                 {'city_code': '79', 'city_name': '淮安'},
                 {'city_code': '80', 'city_name': '宿迁'},
                 {'city_code': '81', 'city_name': '泰州'},
                 {'city_code': '88', 'city_name': '连云港'},
                 {'city_code': '14', 'city_name': '石家庄'},
                 {'city_code': '26', 'city_name': '唐山'},
                 {'city_code': '255', 'city_name': '张家口'},
                 {'city_code': '16', 'city_name': '杭州'},
                 {'city_code': '20', 'city_name': '绍兴'},
                 {'city_code': '28', 'city_name': '宁波'},
                 {'city_code': '111', 'city_name': '台州'},
                 {'city_code': '112', 'city_name': '金华'},
                 {'city_code': '113', 'city_name': '湖州'},
                 {'city_code': '114', 'city_name': '温州'},
                 {'city_code': '168', 'city_name': '嘉兴'},
                 {'city_code': '279', 'city_name': '舟山'},
                 {'city_code': '280', 'city_name': '丽水'},
                 {'city_code': '18', 'city_name': '大连'},
                 {'city_code': '24', 'city_name': '沈阳'},
                 {'city_code': '40', 'city_name': '抚顺'},
                 {'city_code': '44', 'city_name': '鞍山'},
                 {'city_code': '47', 'city_name': '本溪'},
                 {'city_code': '48', 'city_name': '铁岭'},
                 {'city_code': '49', 'city_name': '辽阳'},
                 {'city_code': '54', 'city_name': '丹东'},
                 {'city_code': '55', 'city_name': '盘锦'},
                 {'city_code': '56', 'city_name': '锦州'},
                 {'city_code': '106', 'city_name': '葫芦岛'},
                 {'city_code': '230', 'city_name': '朝阳'},
                 {'city_code': '282', 'city_name': '聊城'},
                 {'city_code': '139', 'city_name': '安庆'},
                 {'city_code': '175', 'city_name': '马鞍山'},
                 {'city_code': '219', 'city_name': '池州'},
                 {'city_code': '90', 'city_name': '西安'},
                 {'city_code': '272', 'city_name': '汉中'},
                 {'city_code': '273', 'city_name': '咸阳'},
                 {'city_name': '福州', 'city_code': '91'},
                 {'city_name': '厦门', 'city_code': '92'},
                 {'city_name': '泉州', 'city_code': '93'},
                 {'city_name': '宁德', 'city_code': '276'},
                 {'city_name': '海外地产', 'city_code': '220'}]

all_city_code_url = [
    {'city_code': '1', 'city_name': '北京', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=bj'},
    {'city_code': '2', 'city_name': '上海', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=sh'},
    {'city_code': '36', 'city_name': '重庆', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=cq'},
    {'city_code': '57', 'city_name': '天津', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=tianjin'},
    {'city_code': '3', 'city_name': '广州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=gz'},
    {'city_code': '4', 'city_name': '深圳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=sz'},
    {'city_code': '37', 'city_name': '中山', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zs'},
    {'city_code': '38', 'city_name': '珠海', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zh'},
    {'city_code': '39', 'city_name': '江门', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=jm'},
    {'city_code': '41', 'city_name': '惠州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=huizhou'},
    {'city_code': '42', 'city_name': '东莞', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=dg'},
    {'city_code': '43', 'city_name': '佛山', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=fs'},
    {'city_code': '89', 'city_name': '清远', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=qingyuan'},
    {'city_code': '150', 'city_name': '湛江', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zhanjiang'},
    {'city_code': '151', 'city_name': '阳江', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=yangjiang'},
    {'city_code': '152', 'city_name': '茂名', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=maoming'},
    {'city_code': '153', 'city_name': '肇庆', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zhaoqing'},
    {'city_code': '169', 'city_name': '汕头', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=shantou'},
    {'city_code': '170', 'city_name': '潮州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=chaozhou'},
    {'city_code': '171', 'city_name': '汕尾', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=shanwei'},
    {'city_code': '172', 'city_name': '揭阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=jieyang'},
    {'city_code': '173', 'city_name': '梅州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=meizhou'},
    {'city_code': '181', 'city_name': '云浮', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=yunfu'},
    {'city_code': '248', 'city_name': '韶关', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=shaoguan'},
    {'city_code': '5', 'city_name': '成都', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=cd'},
    {'city_code': '29', 'city_name': '南充', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=nanchong'},
    {'city_code': '30', 'city_name': '泸州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=lz'},
    {'city_code': '31', 'city_name': '绵阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=my'},
    {'city_code': '258', 'city_name': '内江', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=neijiang'},
    {'city_code': '261', 'city_name': '乐山', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=leshan'},
    {'city_code': '6', 'city_name': '武汉', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=wh'},
    {'city_code': '95', 'city_name': '宜昌', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=yichang'},
    {'city_code': '143', 'city_name': '襄阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xiangyang'},
    {'city_code': '185', 'city_name': '恩施', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=enshi'},
    {'city_code': '186', 'city_name': '黄石', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=huangshi'},
    {'city_code': '187', 'city_name': '黄冈', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=huanggang'},
    {'city_code': '188', 'city_name': '鄂州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=ezhou'},
    {'city_code': '227', 'city_name': '荆州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=jingzhou'},
    {'city_code': '228', 'city_name': '十堰', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=shiyan'},
    {'city_code': '232', 'city_name': '荆门', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=jingmen'},
    {'city_code': '233', 'city_name': '仙桃', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xiantao'},
    {'city_code': '236', 'city_name': '孝感', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xiaogan'},
    {'city_code': '242', 'city_name': '咸宁', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xianning'},
    {'city_code': '7', 'city_name': '长沙', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=cs'},
    {'city_code': '21', 'city_name': '株洲', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zhuzhou'},
    {'city_code': '22', 'city_name': '衡阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=hengyang'},
    {'city_code': '121', 'city_name': '湘潭', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xiangtan'},
    {'city_code': '123', 'city_name': '郴州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=chenzhou'},
    {'city_code': '128', 'city_name': '永州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=yongzhou'},
    {'city_code': '130', 'city_name': '岳阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=yueyang'},
    {'city_code': '131', 'city_name': '常德', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=changde'},
    {'city_code': '132', 'city_name': '益阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=yiyang'},
    {'city_code': '283', 'city_name': '邵阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=shaoyang'},
    {'city_code': '12', 'city_name': '郑州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zz'},
    {'city_code': '269', 'city_name': '驻马店', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zhumadian'},
    {'city_code': '141', 'city_name': '洛阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=luoyang'},
    {'city_code': '162', 'city_name': '南阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=nanyang'},
    {'city_code': '164', 'city_name': '许昌', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xuchang'},
    {'city_code': '167', 'city_name': '开封', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=kaifeng'},
    {'city_code': '245', 'city_name': '平顶山',
     'city_url': 'http://db.house.qq.com/index.php?mod=search&city=pingdingshan'},
    {'city_code': '246', 'city_name': '漯河', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=luohe'},
    {'city_code': '259', 'city_name': '周口', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zhoukou'},
    {'city_code': '13', 'city_name': '南京', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=nj'},
    {'city_code': '51', 'city_name': '苏州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=suzhou'},
    {'city_code': '52', 'city_name': '无锡', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=wuxi'},
    {'city_code': '53', 'city_name': '常州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=changzhou'},
    {'city_code': '67', 'city_name': '扬州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=yangzhou'},
    {'city_code': '68', 'city_name': '镇江', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zhenjiang'},
    {'city_code': '69', 'city_name': '南通', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=nantong'},
    {'city_code': '70', 'city_name': '徐州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xuzhou'},
    {'city_code': '71', 'city_name': '盐城', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=yancheng'},
    {'city_code': '79', 'city_name': '淮安', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=huaian'},
    {'city_code': '80', 'city_name': '宿迁', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=suqian'},
    {'city_code': '81', 'city_name': '泰州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=taizhou'},
    {'city_code': '88', 'city_name': '连云港', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=lianyungang'},
    {'city_code': '14', 'city_name': '石家庄', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=sjz'},
    {'city_code': '26', 'city_name': '唐山', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=tangshan'},
    {'city_code': '255', 'city_name': '张家口', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zjk'},
    {'city_code': '16', 'city_name': '杭州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=hz'},
    {'city_code': '20', 'city_name': '绍兴', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=shaoxing'},
    {'city_code': '28', 'city_name': '宁波', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=nb'},
    {'city_code': '111', 'city_name': '台州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=tz'},
    {'city_code': '112', 'city_name': '金华', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=jinhua'},
    {'city_code': '113', 'city_name': '湖州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=huzhou'},
    {'city_code': '114', 'city_name': '温州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=wenzhou'},
    {'city_code': '168', 'city_name': '嘉兴', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=jiaxing'},
    {'city_code': '279', 'city_name': '舟山', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=zhoushan'},
    {'city_code': '280', 'city_name': '丽水', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=ls'},
    {'city_code': '18', 'city_name': '大连', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=dl'},
    {'city_code': '24', 'city_name': '沈阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=sy'},
    {'city_code': '40', 'city_name': '抚顺', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=fushun'},
    {'city_code': '44', 'city_name': '鞍山', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=anshan'},
    {'city_code': '47', 'city_name': '本溪', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=benxi'},
    {'city_code': '48', 'city_name': '铁岭', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=tl'},
    {'city_code': '49', 'city_name': '辽阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=ly'},
    {'city_code': '54', 'city_name': '丹东', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=dandong'},
    {'city_code': '55', 'city_name': '盘锦', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=panjin'},
    {'city_code': '56', 'city_name': '锦州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=jinzhou'},
    {'city_code': '106', 'city_name': '葫芦岛', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=huludao'},
    {'city_code': '230', 'city_name': '朝阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=chaoyang'},
    {'city_code': '282', 'city_name': '聊城', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=lc'},
    {'city_code': '139', 'city_name': '安庆', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=anqing'},
    {'city_code': '175', 'city_name': '马鞍山', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=maanshan'},
    {'city_code': '219', 'city_name': '池州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=chizhou'},
    {'city_code': '90', 'city_name': '西安', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xian'},
    {'city_code': '272', 'city_name': '汉中', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=hanzhong'},
    {'city_code': '273', 'city_name': '咸阳', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xy'},
    {'city_code': '91', 'city_name': '福州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=fuzhou'},
    {'city_code': '92', 'city_name': '厦门', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=xiamen'},
    {'city_code': '93', 'city_name': '泉州', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=quanzhou'},
    {'city_code': '276', 'city_name': '宁德', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=ningde'},
    {'city_code': '220', 'city_name': '海外地产', 'city_url': 'http://db.house.qq.com/index.php?mod=search&city=haiwai'}]

